name: logbook
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  supabase: ^0.2.6
  google_sign_in: ^5.1.0
  cloud_firestore: ^3.1.17
  intl: ^0.17.0
  firebase_core: ^1.6.0
  firebase_auth: ^3.3.18
  shared_preferences: ^2.0.8
  provider: ^6.0.1
  json_annotation: ^4.1.0
  geocoding: ^2.0.4
  geolocator: ^8.2.1
  flutter_map: ^0.14.0
  step_progress_indicator: ^1.0.2
  rflutter_alert: ^2.0.4

dev_dependencies:
  json_serializable: ^5.0.2
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/

 
